# Site settings
title: projects.zackurtz
email: me@zackurtz.com
description: > # this means to ignore newlines until "baseurl:"
  Some of my projects are here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zackurtz.github.io" # the base hostname & protocol for your site
twitter_username: zackurtz
github_username:  zackurtz

# Build settings
markdown: kramdown
